### ISSUE TITLE
Create an example with an input template and input validation

### ISSUE THREAD

**Issue by bast** [dev-cafe/parselglossy#2]
[Pasting here notes from our meeting last week]

- While the tool will allow "any" grammar, try to express the input structure as YAML.
- Keywords require to be documented.
- Demonstrate a cross-section validation.
- In validation we can use predicates which allow "any" valid Python.
- Keywords either have defaults or are required.

**Comment by bast** [comment]
Here is a suggestion for an input template. So far there are no predicates for validation. First I want to get a good starting structure. Feedback very welcome.

```yml
keywords:
  - keyword: title
    type: str
    documentation: |
      Title of the calculation.
      Since there is no default, this keyword is required.
sections:
  - section: scf
    keywords:
    - keyword: max_num_iterations
      type: int
      default: 20
      documentation: |
        Max number of iterations.
    - keyword: some_acceleration
      type: bool
      default: False
      documentation: |
        Turn on the new amazing acceleration scheme.
    sections:
    - section: thresholds
      keywords:
      - keyword: some_integral_screening
        type: float
        default: 0.0001
        documentation: |
          Some integral based threshold.
      - keyword: energy
        type: float
        default: 0.001
        documentation: |
          Some energy based threshold.
```

**Comment by robertodr** [comment]
**WARNING** This is not a comment on the format, but a summary of the scope of this library. I post it here as it seems pertinent to steering the discussion, but feel free to move it to another RFC issue.

The following is the expected structure of this library, with the relation between components.

![parselglossy](https://user-images.githubusercontent.com/3708689/52522925-ce9d4380-2c8b-11e9-9cd0-52de4be49ff3.jpg)

@bast is no requesting comments on (RFC == Request For Comments) is the right-hand side of the figure, that is the _validation specification_ (_vspecs_).

From parsing to validation, I outline two routes:
1) the lower one is file-based. Input file -> PARSER -> Intermediate Representation (IR) -> VALIDATOR (and vspecs) -> Final representation (FR)
2) the upper one is "data-based", meaning that it relies on nested Python `dict`-s rather than their file serialization. The upper route can bypass the PARSER element of the library and gives full scriptable access to setting input parameters.

Intermediate (IR) and Final (FR) Representations _must be_ in formats that are valid serializations of the Python `dict` data structure. JSON has been temporarily chosen for the IR as the `json` module is part of the default Python distribution, contrary to YAML. It is an open question whether we want to allow users of `parselglossy` to use different formats for one or both the IR and the FR. While this is not an insurmountable technical challenge, it does not seem (to me, at least) to be a feature to die for.
Program authors will have to depend on an implementation of a serialized FR reader. JSON again seems to be favorable as mature and actively maintained implementations are available for all the major compiled languages (C, C++ and Fortran) used in the domain that is our target.

To allow for its flexible use, the library will have two components the _parser_ and the _validator_.
Assuming, but not requiring, that the code that needs input parsing facilities is _scriptable_, these are some the scenarios we want to tackle. :
- **User** Writes an input file, runs a wrapper script to a program, gets an output. Program authors will have to interact with `parselglossy` to:
     a. Define the input grammar (`import parselglossy.parser`)
     b. Define the vspecs
     c. Define the combination of vspecs (`import parselglossy.validator`)
- **Power user** Writes a script with input options as a Python `dict`. These are passed as-is to the VALIDATOR which fills in the gaps (defaults, missing required values and so forth) and then forwards for actual execution. Program authors will have to interact with `parselglossy` to:
     a. Orchestrate invocation of the VALIDATOR 
     b. Forward the validated `dict` for execution.

**Comment by bast** [comment]
Suggestion: the validator receives a dict or JSON and does not know whether this was read from file or not. It then compares it with a template which again is a dictionary, read from another file. But again it does not matter to the validator where the template dictionary came from.

**Comment by robertodr** [comment]
I agree with the suggestion, but I think the template can be generated automatically from the `vspec`s, rather than written down explicitly _in addition_ to them. The validated FR can then be generated by merging (interpolating? Not sure about the right word here) the IR with the template FR.
![validator](https://user-images.githubusercontent.com/3708689/52647890-d35d3400-2ee5-11e9-9508-498d2fd96ef0.png)

**Comment by robertodr** [comment]
- The `vspec` should also have a `range` field, I think, accepting an array: `range: [lower, upper]`
- What types are we supporting? I would say `bool`, `int`, `float`, `complex`, `str` and arrays thereof.

**Comment by bast** [comment]
As to types: yes.

My understanding until now was that `vspec` is expressed as YAML which then was my template suggestion above. But perhaps I misunderstood? Where/how will the developers of the codes that will use this lib define keywords and sections and expected types and so on? I assumed that in a YAML. We can also assume that we don't know and that we get a specification JSON? My question boils down to: how will `vspec` look in practice?

**Comment by robertodr** [comment]
We're on the same page, I misunderstood your suggestion. In my head the `vspec` will look exactly as you wrote it down. The VALIDATOR component will read the YAML and then iterate over it to collate the validation and documentation generation scripts. Indeed having a "template FR" still duplicates work, even if autogenerated.

**Comment by bast** [comment]
OK so I can go ahead creating a validation example based on my template? For my example I will assume that the grammar is YAML but then later this will be replaced by JSON which is obtained using the actual grammar.

**Comment by robertodr** [comment]
Yes, please! :confetti_ball:

**Comment by bast** [comment]
We should move the general layout pictures to own issue/PR/documentation so that it does not get lost once the validation is merged.

**Comment by robertodr** [comment]
Yes, will open a PR shortly.

**Comment by bast** [comment]
The designs are now in the docs: https://parselglossy.readthedocs.io/en/latest/design.html - nice!

**Comment by bast** [comment]
> * The `vspec` should also have a `range` field, I think, accepting an array: `range: [lower, upper]`

Can you please provide an example for a `range` field? I think I see what you mean but am not sure. How would it look on the template side? How would it look on the input side (ignoring the grammar for the moment)?

**Comment by robertodr** [comment]
Input side:
```
foo = 0.90
```
Vspec side:
```
keywords:
  - keyword: foo
    type: 
      - float
      - range: [0.0, 1.0]
```
and the checks on the type would be something like
```
if ir['foo'] in keywords['foo']['range'] and isinstance(ir['foo'], keywords['foo']['type'])
```
probably the check can be done more elegantly with `all` and some functional transformations of the list `keywords['foo']['type']`

So the range should go in the type specification. Just having the type means anything in the range accepted by Python for the internal type representation.

**Comment by bast** [comment]
But should the range not be checked with predicates for more generality? In other words checking the range would be like any other consistency check, internal or across sections.

**Comment by robertodr** [comment]
I think of it as type information, so it would belong under `type` IMHO and be an autogenerate predicate (like the predicate checking that documentation exists)

**Comment by bast** [comment]
I was considering doing it like this (doc strings left out for simplicity):
```yaml
- keyword: some_number
  type: int
  default: 20
  predicates:
    - '0 <= value <= 40'
    - 'value % 2 == 0'
    - ...  # some cross-keyword validation also
- keyword: some_text
  type: str
  default: 'example text'
  predicates:
    - 'len(value) <= 80'
```
This would have the advantage that you can define whatever predicate, not just range.
`value` would refer to the input value.
