### ISSUE TITLE
Get default value from other keyword

### ISSUE THREAD

**Issue by stigrj** [dev-cafe/parselglossy#31]
### Description
It would be great to have the possibility to use keyword values as defaults for other related keywords. Something like this in the predicate syntax:
```
keywords:
  - keyword: precision
    type: float
    default: 1.0e-6
  - keyword: threshold
    type: float
    default: "value = 10 * input_dict['precision']"
```
