### ISSUE TITLE
Omitting sections with all defaults

### ISSUE THREAD

**Issue by stigrj** [dev-cafe/parselglossy#33]
* parselglossy version: b51e249dcbf5fb
* Python version: 3.7.0
* Operating System: Ubuntu-18.10

### Description

It seems like it's not possible to omit sections entirely even if all their keywords have default values.

### What I Did
The following input.yml
```
foobar: false
```
validated with this template.yml
```
keywords:
  - keyword: foobar
    type: bool
    documentation: |
      foobar
sections:
  - section: foo
    keywords:
      - keyword: bar
        type: bool
        default: true
        documentation: |
          foo.bar
```
gives the following error:
```
    input_dict = validate_node(input_dict, template_dict)
  File "parselglossy/validate.py", line 168, in validate_node
    input_section = input_dict[section]
KeyError: 'foo'
```
