### ISSUE TITLE
Chain of dependencies

### ISSUE THREAD

**Issue by stigrj** [dev-cafe/parselglossy#76]
### Description

The following chain of dependencies currently does not work if neither `bar` nor `baz` is set:
```
keywords:
  - name: foo                                                             
    type: float                                                                  
    docstring: "Foo"
  - name: bar
    type: float
    default: "user['foo']"
    docstring: "Bar"
  - name: baz
    type: float
    default: "user['bar']"
    docstring: "Baz"
```
It seems `baz` is first set equal to the string `"user['foo']"` (which is a type mismatch), *before* `bar` is set to the value of `foo`. Related to issue #73.
